import type React from "react";
import { Activity, BarChart3, Bell, Bookmark, Boxes, Building2, Calendar, ClipboardList, Clock, Cpu, Database, Eye, EyeOff, Factory, FileCog, FileText, Filter, Flag, Folder, FolderTree, Gauge, Grid3X3, Home, KeyRound, Layers, LayoutDashboard, LineChart, ListTree, Lock, Map, MapPin, Package, PieChart, Search, Server, Settings, Shield, Star, Table, TrendingUp, Truck, UserCog, Users, Workflow, Wrench } from "lucide-react";

const iconMap: Record<string, React.ReactNode> = {
  dashboard: <LayoutDashboard className="size-4" />,
  database: <Database className="size-4" />,
  users: <Users className="size-4" />,
  settings: <Settings className="size-4" />,
  menu: <Table className="size-4" />,
  file: <FileText className="size-4" />,

  LayoutDashboard: <LayoutDashboard className="size-4" />,
  Home: <Home className="size-4" />,
  Settings: <Settings className="size-4" />,
  Users: <Users className="size-4" />,
  UserCog: <UserCog className="size-4" />,
  Shield: <Shield className="size-4" />,
  Database: <Database className="size-4" />,
  Table: <Table className="size-4" />,
  Folder: <Folder className="size-4" />,
  FolderTree: <FolderTree className="size-4" />,
  FileText: <FileText className="size-4" />,
  ClipboardList: <ClipboardList className="size-4" />,
  BarChart: <BarChart3 className="size-4" />,
  LineChart: <LineChart className="size-4" />,
  PieChart: <PieChart className="size-4" />,
  TrendingUp: <TrendingUp className="size-4" />,
  Activity: <Activity className="size-4" />,
  Bell: <Bell className="size-4" />,
  Calendar: <Calendar className="size-4" />,
  Clock: <Clock className="size-4" />,
  Search: <Search className="size-4" />,
  Filter: <Filter className="size-4" />,
  Layers: <Layers className="size-4" />,
  Grid3X3: <Grid3X3 className="size-4" />,
  Package: <Package className="size-4" />,
  Truck: <Truck className="size-4" />,
  Map: <Map className="size-4" />,
  MapPin: <MapPin className="size-4" />,
  Building2: <Building2 className="size-4" />,
  Factory: <Factory className="size-4" />,
  Wrench: <Wrench className="size-4" />,
  Cpu: <Cpu className="size-4" />,
  Server: <Server className="size-4" />,
  KeyRound: <KeyRound className="size-4" />,
  Lock: <Lock className="size-4" />,
  Eye: <Eye className="size-4" />,
  EyeOff: <EyeOff className="size-4" />,
  Bookmark: <Bookmark className="size-4" />,
  Star: <Star className="size-4" />,
  Flag: <Flag className="size-4" />,
  FileCog: <FileCog className="size-4" />,
  ListTree: <ListTree className="size-4" />,
  Boxes: <Boxes className="size-4" />,
  Workflow: <Workflow className="size-4" />,
  Gauge: <Gauge className="size-4" />,
};

export function resolveMenuIcon(name: string) {
  return iconMap[name] ?? iconMap.FileText;
}
